### ISSUE TITLE
Crashes Atom when used with autocomplete-plus

### ISSUE THREAD

**Issue by ProLoser** [abe33/atom-pigments#7]
When used with autocomplete-plus only, simply writing a few characters in a `scss` file causes the entire editor to crash.

See https://github.com/atom-community/autocomplete-plus/issues/429

**Comment by abe33** [comment]
Thanks for the reports, Can you give some basic details about your configuration like the version of Atom, autocomplete-plus and pigments?

I'm not able to reproduce that with the latest version of all packages.

**Comment by ProLoser** [comment]
It happens when I start to type inside an SCSS file.

**Comment by ProLoser** [comment]
Despite this list, I've actually disabled all third-party plugins except autocomplete-plus and pigments. I also updated to the latest version compared to the versions mentioned in the linked-to issue.

```
 ~/S/main-app   signup-reshuffle   apm list
Built-in Atom packages (85)
├── archive-view@0.56.0
├── atom-dark-syntax@0.26.0
├── atom-dark-ui@0.49.0
├── atom-light-syntax@0.26.0
├── atom-light-ui@0.41.0
├── autocomplete@0.44.0
├── autoflow@0.22.0
├── autosave@0.20.0
├── background-tips@0.24.0
├── base16-tomorrow-dark-theme@0.25.0
├── base16-tomorrow-light-theme@0.8.0
├── bookmarks@0.35.0
├── bracket-matcher@0.74.0
├── command-palette@0.35.0
├── deprecation-cop@0.43.0
├── dev-live-reload@0.46.0
├── encoding-selector@0.20.0
├── exception-reporting@0.24.0
├── feedback@0.38.0
├── find-and-replace@0.161.0
├── fuzzy-finder@0.83.0
├── git-diff@0.55.0
├── go-to-line@0.30.0
├── grammar-selector@0.46.0
├── image-view@0.54.0
├── incompatible-packages@0.24.0
├── keybinding-resolver@0.32.0
├── language-c@0.44.0
├── language-clojure@0.14.0
├── language-coffee-script@0.40.0
├── language-csharp@0.5.0
├── language-css@0.28.0
├── language-gfm@0.70.0
├── language-git@0.10.0
├── language-go@0.25.0
├── language-html@0.32.0
├── language-hyperlink@0.13.0
├── language-java@0.15.0
├── language-javascript@0.76.0
├── language-json@0.14.0
├── language-less@0.26.0
├── language-make@0.14.0
├── language-mustache@0.11.0
├── language-objective-c@0.15.0
├── language-perl@0.23.0
├── language-php@0.22.0
├── language-property-list@0.8.0
├── language-python@0.34.0
├── language-ruby@0.52.0
├── language-ruby-on-rails@0.21.0
├── language-sass@0.36.0
├── language-shellscript@0.14.0
├── language-source@0.9.0
├── language-sql@0.15.0
├── language-text@0.6.0
├── language-todo@0.19.0
├── language-toml@0.15.0
├── language-xml@0.28.0
├── language-yaml@0.22.0
├── link@0.30.0
├── markdown-preview@0.148.0
├── metrics@0.45.0
├── notifications@0.42.0
├── one-dark-syntax@0.4.0
├── one-dark-ui@0.7.0
├── one-light-syntax@0.5.0
├── one-light-ui@0.6.0
├── open-on-github@0.36.0
├── package-generator@0.38.0
├── release-notes@0.52.0
├── settings-view@0.196.0
├── snippets@0.88.0
├── solarized-dark-syntax@0.32.0
├── solarized-light-syntax@0.19.0
├── spell-check@0.56.0
├── status-bar@0.69.0
├── styleguide@0.44.0
├── symbols-view@0.95.0
├── tabs@0.68.0
├── timecop@0.31.0
├── tree-view@0.171.0
├── update-package-dependencies@0.9.0
├── welcome@0.27.0
├── whitespace@0.29.0
└── wrap-guide@0.32.0

/Users/Dean/.atom/packages (24)
├── autoclose-html@0.15.0
├── autocomplete-css@0.6.0
├── autocomplete-html@0.6.0
├── autocomplete-paths@1.0.2
├── autocomplete-plus@2.12.1
├── autocomplete-ruby@0.1.0
├── color-picker@1.7.0
├── docblockr@0.6.3
├── emmet@2.3.8
├── file-icons@1.5.5
├── git-blame@0.4.2
├── git-control@0.2.0
├── git-history@2.5.0
├── language-haml@0.20.0
├── linter@0.12.1
├── linter-jshint@0.1.2
├── linter-rubocop@0.2.3
├── linter-scss-lint@0.0.14
├── livereload@0.2.0
├── minimap-git-diff@4.1.2
├── pepper-autocomplete@0.6.0
├── pigments@0.2.0
├── react@0.11.8
└── tualo-git-context@0.6.2
```

**Comment by abe33** [comment]
@ProLoser: I'm really sorry for the inconvenience, I'll need you to answer some additional questions as I'm still looking for a way to reproduce this problem: 

Does it crashes instantly or does it freezes and displays the *Editor not responding* dialog?
Do you work on a large project? By large project I mean one with lots of scss/sass files, lots of variables, etc.
Does the other pigments features works? Like showing the pallette or finding all colors.
Does it still crash if you disable the `Extend Autocomplete To Variables` setting?

I'll probably come up with other questions as they'll pop up.

**Comment by ProLoser** [comment]
It freezes and displays _editor not responding_

Yes, it's a fairly big project, and yes, lots of files and variables.

Yes, other features work.

`Extend Autocomplete To Variables` wasn't even enabled, I just have default config.

I can open a scss file and be fine, but as soon as I type 4 characters the editor locks up. This seems to be consistently around 4 characters or the amount of time it takes to type that many.

**Comment by ProLoser** [comment]
So my guess (poking around settings) is that a scan is being initiated and I just have too big of a project so it's locking up the editor. Is there any way to do some sort of indexing in a web-worker or relegate this to a background process?

**Comment by eliasyanni** [comment]
Agreed editor lockup due to large project or file.

### steps to reproduce:

1. Choice a CSS or LESS file
2. Add a property and color value

**Atom Version**: 0.196.0
**System**: Mac OS X 10.10.3
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.2.0

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /Users/[username]/.atom/packages/pigments/lib/regexes.coffee:0

RangeError: Maximum call stack size exceeded
  at String.replace (native)
  at /Users/[username]/.atom/packages/pigments/lib/regexes.coffee:23:14
  at Array.map (native)
  at module.exports.createVariableRegExpString (/Users/[username]/.atom/packages/pigments/lib/regexes.coffee:22:31)
  at module.exports.getRegistry (/Users/[username]/.atom/packages/pigments/lib/color-expressions.coffee:628:27)
  at ColorParser.module.exports.ColorParser.parse (/Users/[username]/.atom/packages/pigments/lib/color-parser.coffee:18:16)
  at ColorContext.module.exports.ColorContext.readColor (/Users/[username]/.atom/packages/pigments/lib/color-context.coffee:41:22)
 
  at Color.<anonymous> (/Users/[username]/.atom/packages/pigments/lib/color-expressions.coffee:339:25)
  at ColorExpression.module.exports.ColorExpression.parse (/Users/[username]/.atom/packages/pigments/lib/color-expression.coffee:15:13)
  at ColorParser.module.exports.ColorParser.parse (/Users/[username]/.atom/packages/pigments/lib/color-parser.coffee:21:16)
  at ColorContext.module.exports.ColorContext.readColor (/Users/[username]/.atom/packages/pigments/lib/color-context.coffee:41:22)



  at ProjectVariable.module.exports.ProjectVariable.readColor (/Users/[username]/.atom/packages/pigments/lib/project-variable.coffee:22:39)
  at ProjectVariable.module.exports.ProjectVariable.getColor (/Users/[username]/.atom/packages/pigments/lib/project-variable.coffee:18:27)
  at ProjectVariable.module.exports.ProjectVariable.isColor (/Users/[username]/.atom/packages/pigments/lib/project-variable.coffee:16:15)
  at /Users/[username]/.atom/packages/pigments/lib/color-project.coffee:244:69
  at Array.filter (native)
  at ColorProject.module.exports.ColorProject.getColorVariables (/Users/[username]/.atom/packages/pigments/lib/color-project.coffee:244:39)
  at PigmentsProvider.module.exports.PigmentsProvider.getSuggestions (/Users/[username]/.atom/packages/pigments/lib/pigments-provider.coffee:27:28)
  at /Users/[username]/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:152:45
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Users/[username]/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:135:15)
  at AutocompleteManager.getSuggestionsFromProviders (/Users/[username]/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Users/[username]/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:129:6)
  at /Users/[username]/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1

```

### Commands

```
     -4:38.1.0 core:confirm (atom-text-editor.editor.mini)
     -4:38.1.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -4:16.2.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -4:12 core:confirm (atom-text-editor.editor.mini)
     -3:18.8.0 emmet:balance-outward (atom-text-editor.editor)
     -3:17.5.0 core:backspace (atom-text-editor.editor)
     -3:15.9.0 core:save (atom-text-editor.editor)
     -0:34.1.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:25.7.0 find-and-replace:focus-next (atom-text-editor.editor.mini)
     -0:23.9.0 find-and-replace:find-next (atom-text-editor.editor.mini)
     -0:19.6.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:19.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:19 core:paste (atom-text-editor.editor.is-focused)
     -0:18.5.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:18.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:18.2.0 core:paste (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tabs",
      "tree-view"
    ],
    "themes": [
      "isotope-ui",
      "one-dark-syntax"
    ]
  },
  "pigments": {
    "sortPaletteColors": "by color"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-beautify, v0.27.0
autoclose-html, v0.15.0
autocomplete-css, v0.6.0
autocomplete-html, v0.6.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.1
color-picker, v1.7.0
composer, v0.3.1
emmet, v2.3.8
highlight-selected, v0.9.2
isotope-ui, v2.1.5
language-apache, v1.3.0
local-server-express, v0.3.1
minimap, v4.8.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.1
pigments, v0.2.0
project-manager, v1.15.5
sublime-tabs, v0.5.6

# Dev
No dev packages
```

**Comment by abe33** [comment]
Thanks both of you for the details,

@ProLoser: I'm using a `Task` for mostly every heavy stuff (finding the paths, scanning the paths for variables, scanning the buffer for variables and colors) so it should already be off the main thread. But maybe it's on the event reception that something get messed up.

@ProLoser, @eliasyanni Does the projects that cause pigments to crash Atom are publicly available? I'll be interested in reproducing it myself.

**Comment by ProLoser** [comment]
Maybe look at the sass/foundation source files, in a file that includes all the others, and try typing into that file with autocomplete-plus enabled.

**Comment by abe33** [comment]
Ok guys, I've been able to reproduce it using compass sources. I still haven't found the reason why it crashes, so stay tuned.

**Comment by abe33** [comment]
I just published a new version that at least fixes crashes when I open compass. 
The variables parser was catching too much things like mixins and functions declarations (which can have default values for arguments). 
For compass, for instance, the number of variable found dropped from 1100+ to 230. And when converting these variables to colors it probably entered in an infinite loop.

Let me know if it's more stable now on your respective projects.

**Comment by ProLoser** [comment]
Nope, still crashing.

**Comment by micnigh** [comment]
We've run into this issue and had some success tracking it down.

In our case the crash happened due to including variables from `node_modules` which pushed the variable count to 2400+.  Then pigments must be entering an infinite loop as the stack overflows shortly after starting the autocomplete process.

Our current workaround is to disable searching in `node_modules` in our config 
```coffee
"*":
  core:
    ignoredNames: [
      "**node_modules**"
    ]
```

We also had to delete `$HOME/.atom/storage/editor-*` to remove cached variables.

**Comment by ProLoser** [comment]
@abe33 actually I was wrong, I think your fix solved the problem. @micnigh I think all that was needed was to remove the cached variables, try it without ignoring node_modules. I had to make sure to clear cache before it started working again.

**Comment by micnigh** [comment]
I tried clearing my cached variables and running without ignoring `node_modules` but the editor would still crash for me.

@abe33 
If it helps I can see about setting up a project to reproduce the problem - likely a few days out though.

**Comment by abe33** [comment]
@micnigh For the time being, I think I'll completely exclude `node_modules` by default and add a command to clear the project state so that we doesn't have to touch to storage. 

Anyway, thank you guys for the feedbacks, it's really appreciated :bow:

**Comment by abe33** [comment]
I'll close it as nobody as updated this for months.
